### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by ketdougi** [realjaidhaliwal/Snake#10]
Add tests to ensure our new features/bug fixes doesn't break the current functionality

**Comment by ketdougi** [comment]
Where should these tests be added?

**Comment by vijaivir** [comment]
Maybe its best to create a new branch and add the tests to it first. Then if all works well we can merge it with master.

**Comment by OwenBC** [comment]
@ketdougi You can add tests on this branch (create-unit-tests, #11) as I did with the sample test I've created there.

**Comment by OwenBC** [comment]
Update: Issue is that testing box is headless and doesn't support the GUI objects. Looking into xvfb as a potential solution.  Creating a custom box could be another solution.

**Comment by OwenBC** [comment]
> 


> @ketdougi You can add tests on this branch (create-unit-tests, #11) as I did with the sample test I've created there.

Sooo, it turns out there's some issues with GUI tests and the headless nature of the github actions box. When I get this working it's probably worth merging for use on other dev branches.
