### ISSUE TITLE
Play space has black boxes

### ISSUE THREAD

**Issue by vijaivir** [realjaidhaliwal/Snake#3]
The play space is displaying boxes that don't have any functionality.

**Comment by OwenBC** [comment]
> ![Screen Shot 2022-04-16 at 12 22 11 PM](https://user-images.githubusercontent.com/91633223/163689226-1a672423-b4a0-4544-a203-1f18daafa3cc.png)

Screenshot of this issue from #19

**Comment by OwenBC** [comment]
This seems like it may only be present on Mac machines? I have never seen this issue on Windows (10) or Linux (Pop!_os).

**Comment by vijaivir** [comment]
> This seems like it may only be present on Mac machines? I have never seen this issue on Windows (10) or Linux (Pop!_os).

It's fixed now. It was spawning the head of the second snake.
