### ISSUE TITLE
Score board or game over screen

### ISSUE THREAD

**Issue by ketdougi** [realjaidhaliwal/Snake#5]

**Comment by vijaivir** [comment]
I was trying to add a tiny scoreboard while the game is running but I can't seem to figure out which class I should edit. Does anyone have any ideas on how I can add this feature? @ketdougi @OwenBC

**Comment by OwenBC** [comment]
@realjaidhaliwal You could add a header bar in the `Window` class. I'm not sure how to implement it UI-wise, you'll have to look at the swing docs, but you could make the `snakeSize` variables in `ThreadsController` class `public static` and read that as the score.

**Comment by vijaivir** [comment]
> @realjaidhaliwal You could add a header bar in the `Window` class. I'm not sure how to implement it UI-wise, you'll have to look at the swing docs, but you could make the `snakeSize` variables in `ThreadsController` class `public static` and read that as the score.

Okay thanks I will try to implement this.

**Comment by vijaivir** [comment]
I originally tried to change the Window class to display a live score update but this was resulting in some weird behaviour such as the snake moving diagonally. The best I could do was to create a 'Game Over' pop-up message with the score accumulated in that round. The pop-up also contains a 'Quit' and 'Restart' button allowing for a smoother user experience. 

<img width="258" alt="Screen Shot 2022-04-18 at 7 30 08 PM" src="https://user-images.githubusercontent.com/91633223/163914717-995dab90-a2d8-4e0e-81d4-20d1d6c96461.png">
<img width="261" alt="Screen Shot 2022-04-18 at 7 28 51 PM" src="https://user-images.githubusercontent.com/91633223/163914720-3f493601-e6ab-473c-b001-082391bbfdf7.png">
<img width="262" alt="Screen Shot 2022-04-18 at 7 27 36 PM" src="https://user-images.githubusercontent.com/91633223/163914723-e2f4f191-6c08-4019-9cbd-f3ad255fb7cc.png">
